# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/baddle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/baddle.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\005./rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/baddle.proto\"(\n\nGetWordReq\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\"\x1b\n\x0bGetWordResp\x12\x0c\n\x04word\x18\x01 \x01(\t2.\n\x06\x42\x61\x64\x64le\x12$\n\x07GetWord\x12\x0b.GetWordReq\x1a\x0c.GetWordRespB\x07Z\x05./rpcb\x06proto3'
)




_GETWORDREQ = _descriptor.Descriptor(
  name='GetWordReq',
  full_name='GetWordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GetWordReq.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room', full_name='GetWordReq.room', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=62,
)


_GETWORDRESP = _descriptor.Descriptor(
  name='GetWordResp',
  full_name='GetWordResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='GetWordResp.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['GetWordReq'] = _GETWORDREQ
DESCRIPTOR.message_types_by_name['GetWordResp'] = _GETWORDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetWordReq = _reflection.GeneratedProtocolMessageType('GetWordReq', (_message.Message,), {
  'DESCRIPTOR' : _GETWORDREQ,
  '__module__' : 'proto.baddle_pb2'
  # @@protoc_insertion_point(class_scope:GetWordReq)
  })
_sym_db.RegisterMessage(GetWordReq)

GetWordResp = _reflection.GeneratedProtocolMessageType('GetWordResp', (_message.Message,), {
  'DESCRIPTOR' : _GETWORDRESP,
  '__module__' : 'proto.baddle_pb2'
  # @@protoc_insertion_point(class_scope:GetWordResp)
  })
_sym_db.RegisterMessage(GetWordResp)


DESCRIPTOR._options = None

_BADDLE = _descriptor.ServiceDescriptor(
  name='Baddle',
  full_name='Baddle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWord',
    full_name='Baddle.GetWord',
    index=0,
    containing_service=None,
    input_type=_GETWORDREQ,
    output_type=_GETWORDRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BADDLE)

DESCRIPTOR.services_by_name['Baddle'] = _BADDLE

# @@protoc_insertion_point(module_scope)
